### ISSUE TITLE
how to create the train dataset?

### ISSUE THREAD

**Issue by CauchyHu** [BobbiJ/IM-Net#1]
thanks you greate work!
I have a question about how to create the train dataset ?
can you provide the dataset?
thanks!!!

**Comment by BobbiJ** [comment]
Hi! 
Try this one http://toflow.csail.mit.edu/index.html#triplet

**Comment by CauchyHu** [comment]
> Hi!
> Try this one http://toflow.csail.mit.edu/index.html#triplet

I have solved this question,can you open resource the test.py?
